# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-SPF-Query
version:      1.999.1
version_from: lib/Mail/SPF/Query.pm
installdirs:  site
requires:
    Net::CIDR::Lite:               0.15
    Net::DNS:                      0.46
    Sys::Hostname::Long:           0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
